@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
### use Login api to get token, then copy token after Bearer (with space)
@token = Bearer TOKEN_HERE

################ USER #####################
### Sign up user
POST http://{{host}}/users HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "dt1",
    "password": "123"
}

### Login
POST http://{{host}}/users/login HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "dt1",
    "password": "123"
}



################ PATIENT #####################
### Create
POST http://{{host}}/patients HTTP/1.1
Content-Type: {{contentType}}
authorization: {{token}}

{
    "username": "p1",
    "fullname": "Patient 1",
    "phone": "123456789",
    "avatarUrl": "http://s3.amazon.com/finddoctor/patient/p1.png"
}

### Get all
GET http://{{host}}/patients HTTP/1.1
Content-Type: {{contentType}}
authorization: {{token}}

################ DOCTOR #####################
### Get all
GET http://{{host}}/doctors HTTP/1.1
Content-Type: {{contentType}}
authorization: {{token}}

### Get by username
GET http://{{host}}/doctors/dt1 HTTP/1.1
Content-Type: {{contentType}}

### Search by specialty
GET http://{{host}}/doctors/search?specialty=eye HTTP/1.1
Content-Type: {{contentType}}
authorization: {{token}}

### Update profile
PATCH http://{{host}}/doctors/dt1 HTTP/1.1
Content-Type: {{contentType}}
authorization: {{token}}

{
    "fullname": "Steve Doctor",
    "location": {
        "street": "10 Main street",
        "city": "fairfield",
        "state": "Iowa",
        "zipcode": "52556"
    }
}

################ SPECIALTY #####################
### Get all
GET http://{{host}}/specialties HTTP/1.1
Content-Type: {{contentType}}

### Get by id
GET http://{{host}}/specialties/62ee94a90130159cdfb21206 HTTP/1.1
Content-Type: {{contentType}}

### Create
POST http://{{host}}/specialties HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Dentist",
    "description": "Dentist doctors"
}

### Update
PATCH http://{{host}}/specialties/62ee94a90130159cdfb21206 HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Dentist",
    "description": "Dentist"
}

### Delete by id
DELETE http://{{host}}/specialties/62ee8cf4224bcb9d7b9c306e HTTP/1.1
Content-Type: {{contentType}}